GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

    {
        "title": "third",
        "author": "Drug",
        "url": "te",
        "likes": "45455555"
    }

###
POST http://localhost:3003/api/users
Content-Type: application/json

    {
        "username": "yes",
        "name": "test",
        
    }